// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fovawpvzulethzuqmqqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvdmF3cHZ6dWxldGh6dXFtcXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjU1ODgsImV4cCI6MjA3NjA0MTU4OH0.bbT9Wgbvw-ThXnUJVd4kSUgUquXQMnnevJ85aESiyKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);